apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service-v1
  labels:
    app: book-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-service
      version: v1
  template:
    metadata:
      labels:
        app: book-service
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: book-service
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service-v2
  labels:
    app: book-service
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service
      version: v2
  template:
    metadata:
      labels:
        app: book-service
        version: v2
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: book-service
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: book-service
spec:
  selector:
    app: book-service
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: book-service
spec:
  hosts:
  - book-service
  http:
  - route:
    - destination:
        host: book-service
        subset: v1
      weight: 90
    - destination:
        host: book-service
        subset: v2
      weight: 10
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: book-service
spec:
  host: book-service
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http2MaxRequests: 1000
        maxRequestsPerConnection: 10
    outlierDetection:
      consecutiveErrors: 5
      interval: 30s
      baseEjectionTime: 30s
      maxEjectionPercent: 10
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2 